### PR TITLE
adding a update script....

### PR DESCRIPTION
**Pull request by Blazzycrafter**
But its no restart discord only a kill

### CODE REVIEW

**Comment by suprstarrd** [comment]
This really isn't needed, Powercord has updates built-in

**Comment by Blazzycrafter** [comment]
yeah and discord broke againg one plugin and we CAN´T use the bultin updater -_-

**Comment by pythonmcpi** [comment]
IMO this script is unnecessary. Just run `cd powercord && npm run unplug && git pull && npm i && npm run plug` and you're good to go. Also, powercord is supposed to be cross platform, and this script won't work on Mac or Linux. Also, if we really want an auto update script, it's probably better to make it runnable using the npm command for consistency. (So it would be `npm run update`.)

**Comment by Blazzycrafter** [comment]
yeah that's an idea 💡 but I must lern it...
CLOSED

**Pull request closed without merging**
