### PR TITLE
Fix Overlay DevTools

### PR DESCRIPTION
**Pull request by magistau**

### CODE REVIEW

**Comment by cyyynthia** [comment]
window.\_\_OVERLAY\_\_ is used to identify if the window is actually the overlay or not. You're just making devtools open in literally every Discord window, including main window and go live popout.

**Comment by magistau** [comment]
But wait when should it open it all then?

**Comment by cyyynthia** [comment]
just for Discord overlay

**Comment by magistau** [comment]
You mean the game one?

**Comment by cyyynthia** [comment]
yes.

**Comment by magistau** [comment]
So the Overlay DevTools is for game overlay?

**Comment by cyyynthia** [comment]
yes.

**Comment by magistau** [comment]
nvm I thought it's just a kind of setting to make devtools pop out

**Pull request closed without merging**
