### PR TITLE
Little OCD fix

### PR DESCRIPTION
**Pull request by LandenStephenss**
Whenever you do .help cmd (any command) it says the usage is `/cmd` no matter what. Changed that to use the users prefix

### CODE REVIEW

**Comment by aetheryx** [comment]
the prefix should be included in the monospace opening character, and also, there are far more occurances of the prefix being hardwired as `/`, feel free to try to find them all

**Comment by LandenStephenss** [comment]
Well i'm not sure why i would find them all whenever you can just use `powercord.api.commands.prefix` to display the correct prefix. And the line i changed is still displaying the prefix

image

**Comment by aetheryx** [comment]
> there are far more **occurences of the prefix being hardwired as `/`**  

I'm implying there's more bugs exactly like the one you're fixing in this PR, and you might want to fix all of them instead of just this specific occurence 😄

**Comment by LandenStephenss** [comment]
Ah, alright. Would you like me to find them and add them or you got it?

**Comment by aetheryx** [comment]
I'll take a look later tonight when I'm free before I merge, but you can take a look until then

**Pull request merged**
