### PR TITLE
Check for multiple path in Linux injector

### LINKED ISSUE #70: [Injector] Support multiple installation paths on Linux
I cannot inject Powercord into discord canary, the error I get is this one:
```
$ sudo npm run inject
[sudo] password for yanderella: 

> powercord@1.0.0 inject /home/yanderella/powercord
> node injectors/index.js inject

fucky wucky { Error: ENOENT: no such file or directory, mkdir '/opt/discord-canary/resources/app'
  errno: -2,
  code: 'ENOENT',
  syscall: 'mkdir',
  path: '/opt/discord-canary/resources/app' }
```
I expected powercord to inject successfully by the fact that I have followed all the steps

 - OS: Linux
 - Discord version: Canary 0.0.67

Also, I checked that specified folder and there isn't anything, I installed canary using dpkg via terminal.

### PR DESCRIPTION
**Pull request by intrnl**
Fixes #70

### CODE REVIEW

**Comment by davidcralph** [comment]
when does this get merged?

**Comment by cyyynthia** [comment]
never

**Comment by davidcralph** [comment]
oh

**Comment by aetheryx** [comment]
when @intrnl makes changes that I asked questions about on discord

**Pull request merged**
