### PR TITLE
Fixing "Create in" and Cloning

### PR DESCRIPTION
**Pull request by SammCheese**
Fixes 2 Issues in Emoji Utility

### CODE REVIEW

**Comment by BenSegal855** [comment]
1590 lines changed to comment out a single line. Seems like a bit of overkill to me. ~~or you need to adjust your linter~~

**Comment by SammCheese** [comment]
i uploaded it via web, thats why it shows such a big commit

**Comment by SammCheese** [comment]
Closing, since its been updated

**Comment by cyyynthia** [comment]
As discussed in off-topic, we are 100% unable to accept new contributors due to the perfect contributors count right now. :^)

More seriously, the changes seem to indicate something has gone wrong, and the fix landed in 5d7500d5a4b1f671ad5fecaa5a7a998408b7149e

**Pull request closed without merging**
