### PR TITLE
[Feature Request] Make Powercord Labs look good:tm:. Make it look like other settings

### PR DESCRIPTION
**Pull request by GavynStanley**
This PR makes the Powercord Lab settings look like the other ones. This is only an aesthetic update.

After: New Look

### CODE REVIEW

**Comment by GavynStanley** [comment]
Can I get a further explanation for the application of the invalid tag?

**Comment by GreemDev** [comment]
I'd like one too because I don't see why a purely UI change (that's actually not bad at all) is marked as invalid & closed basically immediately 


EDIT: This was explained (sorta?) in the #powercord-core channel on Discord; however I think it'd be a good idea to have one on this PR otherwise it might scare people off from contributing seeing as a perfectly working PR was closed & marked as invalid with no comment as to why, and people may feel their changes won't get merged so they'll just...not contribute.

**Comment by aetheryx** [comment]
accident ^

**Comment by aetheryx** [comment]
regardless of which page you're contributing to, the changes in this PR are very subjective, and when it comes to subjective changed we highly recommend you _at least_ discuss your changes in the powercord-core channel, or make an issue on GitHub. 

a PR being perfectly working does not mean it's a PR we want to accept. the changes are subjective, and they're changes to Powercord Labs, which currently isn't being focused on at all, and could undergo major changes in the future which would make this PR completely useless...

any people who want to contribute are welcome to do so, but please discuss your changes with a developer so things like these don't happen!

**Comment by GreemDev** [comment]
I appreciate the reply. Is there any particular reason this PR didn't get accepted? The UI changes look fine to me, and if you want to update it in the future, couldn't you just...change it? I don't know, that seems really weird to me as a reason to deny a PR. But I digress.

**Comment by sepruko** [comment]
Again, he mentioned that it is a subjective change, the page works fine as is and no changes need to be made as of now. It isn't like you stare at the page for hours on end, unless that is your kind of thing.

**Comment by MulverineX** [comment]
@GreemDev take a hint
> could undergo major changes in the future which would make this PR completely useless...
> please discuss your changes [beforehand] with a developer

**Comment by GreemDev** [comment]
It is a subjective change, I'm aware of that. I'm just asking why; if there even is a why.

**Comment by MulverineX** [comment]
The "why" is that this person didn't follow due process, period. One shouldn't go along making a change like this without speaking to a dev first.

**Comment by GreemDev** [comment]
> @GreemDev take a hint
> 
> > could undergo major changes in the future which would make this PR completely useless...
> 
> > please discuss your changes [beforehand] with a developer

Again...if it's the old code that you're changing, you'd have to change it anyways.

I'm going to stop replying because this is getting nowhere.

**Comment by GreemDev** [comment]
> The "why" is that this person didn't follow due process, period. One shouldn't go along making a change like this without speaking to a dev first.

Ok then, that's all I was looking for. There's no need to bite my fucking head off over it.

**Comment by aetheryx** [comment]
> The "why" is that this person didn't follow due process, period. One shouldn't go along making a change like this without speaking to a dev first.  

not quite. we accept lots of PRs that weren't discussed with a developer beforehand, e.g. bugfixes or objective improvements to components aside from Powercord Labs. i recommended discussing changes beforehand because we would've been able to reject the idea before time was spent on a PR.  

> I appreciate the reply. Is there any particular reason this PR didn't get accepted? The UI changes look fine to me, and if you want to update it in the future, couldn't you just...change it? I don't know, that seems really weird to me as a reason to deny a PR. But I digress.
> It is a subjective change, I'm aware of that. I'm just asking why; if there even is a why.

the changes are subjective, and they're changes to Powercord Labs, which currently isn't being focused on at all, and could undergo major changes in the future which would make this PR completely useless. even if the UI change is good or not, accepting the PR would've only made sense if it was something we were planning to do ourselves, due to the current state of Powercord Labs.

**Comment by intrnl** [comment]
> Powercord Labs is provided as-is and there's a 50% chance the devs will yell at you for using them and saying your cat is fat.

**Pull request closed without merging**
