### PR TITLE
fixed a typo-

### PR DESCRIPTION
**Pull request by ConnorDoesDev**
im so sorry

### CODE REVIEW

**Comment by Stebulous** [comment]
this is in fact the best pull request

**Comment by ConnorDoesDev** [comment]
i know right

**Review by viermat — APPROVED** [review]

**Comment by viermat** [comment]
> this is in fact the best pull request

Cynthia has a request where she corrects ObjectUrl to ObjectURL which has the commit message "sigh" which I think is funnier

**Comment by ConnorDoesDev** [comment]
lol

**Comment by ConnorDoesDev** [comment]
time to get powercord contributor :D
(actually doing something)

**Pull request merged**
