### PR TITLE
Invite command

### PR DESCRIPTION
**Pull request by ghost**
Added a new command that sends an invite to the Powercord Discord server in the chat you are

### CODE REVIEW

**Comment by NurMarvin** [comment]
Sounds pretty useless to me. Would probably also result in accidental server advertising.
Also, what's so hard about just doing this?
image

**Comment by zt64** [comment]
I agree with @NurMarvin, it would probably be better as a separate plugin.

**Comment by ghost** [comment]
my pc shut down while writing this bruh

I mean it's just to have it handy, it's not something SUUUPER useful, but sometimes it helps
About the accidental server advertising, you're right, maybe I can make it a client-side message with a warning related to that
And about the invite thing, as I said, is just to have it handy

PD: Not entirely sure why the check failed

**Comment by leKamikaze1** [comment]
wait, why did this get closed? reopening

**Comment by ghost** [comment]
wait, why did this get closed? reopening

**Comment by DracoClaw** [comment]
If you really need the invite that often, just create a tag for it.

**Comment by ghost** [comment]
I didn't even know that command existed. Well, guess the invite command is useless then, thanks anyways

**Pull request closed without merging**
