### PR TITLE
Reboot -> Reload in the Updater

### PR DESCRIPTION
**Pull request by brandon9707**

### CODE REVIEW

**Comment by davidcralph** [comment]
was about to comment on the title lol

**Comment by brandon9707** [comment]
yea

**Comment by aetheryx** [comment]
can you elaborate..? what's the point of this?

**Comment by brandon9707** [comment]
Just renaming the "Update & restart" button to "Update & reload", cause it just reload the client and not restarting it :)

**Comment by aetheryx** [comment]
restart is more user-friendly and sensible to non-tech-savvy people, reload is the proper terminology but that doesn't mean it's better

**Comment by brandon9707** [comment]
Makes sense, I'm closing this

**Pull request closed without merging**
